---
title: "Intro_to_SECRET"
output: 
  prettydoc::html_pretty:
    theme: architect
#output: rmarkdown::html_vignette
# vignette: >
#   %\VignetteIndexEntry{Intro_to_SECRET}
#   %\VignetteEngine{knitr::rmarkdown}
#   %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SECRET)
library(tidyverse)
library(alabama)
#load bulk data
bulkdat=read.delim('bulkDat.txt',row.names = 1)
#load cell type reference
refdat=read.delim('refDat.txt',row.names = 1)
#load marker genes, and DEGs between cell types
genelist=read.delim('Genelist.txt')
```

match gene to both bulk and reference data, and calculate weights for each gene based on their occurance among cell types.

```{r}
# count for gene frequency
w=as.data.frame(table(genelist$Genes))
colnames(w)[1]='genes'
rownames(w)=w$genes

### find the shared genes and subset the data
glist=Reduce(intersect,list(rownames(bulkdat),rownames(refdat),genelist$Genes))
w=w[glist,]
bulkdat2<-bulkdat[rownames(bulkdat) %in% w$genes,]
refdat2<-refdat[rownames(refdat) %in% w$genes,]
print(identical(rownames(bulkdat2),rownames(refdat2)))
print(identical(rownames(bulkdat2),rownames(w)))
 
w$weight=1/w$Freq
  
```

Estimate cell type propotion using SECRET
```{r}
wt=w$weight
est_prop=SECRET(bulkdat,refdat2,withUnknown = T,w=wt,yNorm = 'cpm',bNorm='cpm')[[1]]
```

Evaluate the result by comparing with true proportion
```{r}
trueprop=read.csv('TrueProp.csv',row.names = 1)
# rename the unknown cell type to match the name in true proportion
colnames(est_prop)[8]='Oligodendrocytes'
est_prop=est_prop[,colnames(trueprop)]
eval=eval_prop(trueprop,list(SECRET=est_prop))
print(eval)
```

visualize the result
```{r}
true=as.data.frame(trueprop) %>% 
  mutate(sampe=rownames(.)) %>% 
  gather(.,celltype,true_prop,1:8)

est=as.data.frame(est_prop) %>% 
  mutate(sampe=rownames(.)) %>% 
  gather(.,celltype,est_prop,1:8)

dat=cbind(true,est=est$est_prop)

ggplot(dat,aes(x=true_prop,y=est,color=celltype)) +
  geom_point()+geom_abline()+xlab("True Proportion")+
  ylab("Estimated Proportion\n")+theme_bw()+
  theme(legend.position ='bottom',
        legend.title = element_blank())

```


